# Generated by Django 4.2.2 on 2023-09-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_address_alter_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
    ]
