# Generated by Django 4.2 on 2023-06-01 10:17

import backups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_backup_filesize_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='file',
            field=models.FileField(storage=backups.models.MyFileStorage(), upload_to=''),
        ),
    ]
