# Generated by Django 4.2 on 2023-06-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_alter_backup_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='filesize_str',
        ),
    ]
