# Generated by Django 4.2.2 on 2023-09-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0007_alter_backup_options_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
