# Generated by Django 4.2 on 2023-04-06 08:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'NECs',
            },
        ),
        migrations.AlterField(
            model_name='interbankusdrate',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('nec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_info.nec')),
            ],
            options={
                'verbose_name_plural': 'NEC Rates',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('usd_minimum', models.FloatField()),
                ('nec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll_info.nec')),
            ],
            options={
                'verbose_name_plural': 'NEC USD Grades',
            },
        ),
    ]
