# Generated by Django 4.2 on 2023-04-27 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_info', '0002_nec_alter_interbankusdrate_date_rates_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interbankusdrate',
            name='date',
            field=models.DateField(default=datetime.datetime.today, unique=True),
        ),
    ]
